var PAYPAL_SPEC = bankConnectorMakeFillHandlers_({
  sheetName: "Paypal",
  endpoint: "/cron/sync-paypal-transactions",
  action: "fill-paypal",
  menuHandler: "fillPaypalTransactions",
  menuLabel: "Fill Paypal transactions",
  label: "Paypal",
  logPrefix: "fillPaypalTransactions",
  skipReason: "No new Paypal transactions",
  knownIdField: "transactionId",
  sinceDateField: "date",
  yellowHeaders: {
    date: "Date",
    time: "Time",
    timeZone: "TimeZone",
    description: "Description",
    type: "Type",
    status: "Status",
    currency: "Currency",
    gross: "Gross",
    fee: "Fee",
    net: "Net",
    from: "From",
    to: "To",
    transactionId: "Transaction ID",
    referenceTxnId: "Reference Txn ID",
    receiptId: "Receipt ID",
    addressStatus: "Address Status",
    salesTax: "Sales Tax",
    invoiceNumber: "Invoice Number",
    balance: "Balance",
    contactPhoneNumber: "Contact Phone Number",
    subject: "Subject",
    note: "Note",
    balanceImpact: "Balance Impact",
  },
  writeRows: function (sheet, startRow, colMap, transactions) {
    var endRow = startRow + transactions.length - 1;
    var fields = [
      ["date", function (tx) { return tx.date; }],
      ["time", function (tx) { return tx.time; }],
      ["timeZone", function (tx) { return tx.timeZone; }],
      ["description", function (tx) { return tx.description; }],
      ["type", function (tx) { return tx.type; }],
      ["status", function (tx) { return tx.status; }],
      ["currency", function (tx) { return tx.currency; }],
      ["gross", function (tx) { return tx.gross; }],
      ["fee", function (tx) { return tx.fee; }],
      ["net", function (tx) { return tx.net; }],
      ["from", function (tx) { return tx.from; }],
      ["to", function (tx) { return tx.to; }],
      ["transactionId", function (tx) { return tx.transactionId; }],
      ["referenceTxnId", function (tx) { return tx.referenceTxnId; }],
      ["receiptId", function (tx) { return tx.receiptId; }],
      ["addressStatus", function (tx) { return tx.addressStatus; }],
      ["salesTax", function (tx) { return tx.salesTax; }],
      ["invoiceNumber", function (tx) { return tx.invoiceNumber; }],
      ["balance", function (tx) { return tx.balance; }],
      ["contactPhoneNumber", function (tx) { return tx.contactPhoneNumber; }],
      ["subject", function (tx) { return tx.subject; }],
      ["note", function (tx) { return tx.note; }],
      ["balanceImpact", function (tx) { return tx.balanceImpact; }],
    ];
    fields.forEach(function (field) {
      bankConnectorWriteColumn_(sheet, startRow, endRow, colMap[field[0]], transactions, field[1]);
    });
  },
});

function fillPaypalTransactions() { return PAYPAL_SPEC.fillMenu(); }
